name: Publish to Github Pages

on:
  push:
    branches:
      - main

jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: jaywcjlove/markdown-to-html-cli@main
        with:
          source: README.md
          output: index.html
          github-corners: https://github.com/shinwookim/CS0449-StudyGuide
      - name: Deploy
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./
